### PR TITLE
For #18: Update qulice to version 0.17.4.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #18: Update qulice to version 0.17.4.
- Upgraded qulice to version 0.17.4 and corrected failures.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#36](https://github.com/zold-io/java-api/issues/36) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job [#36](https://github.com/zold-io/java-api/issues/36) is already in scope

**Comment by 0crat** [comment]
This pull request [#36](https://github.com/zold-io/java-api/issues/36) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CAZUREFND/1942102030); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#36](https://github.com/zold-io/java-api/issues/36) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#36](https://github.com/zold-io/java-api/issues/36) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#36](https://github.com/zold-io/java-api/issues/36) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't inspect

**Comment by 0crat** [comment]
The job [#36](https://github.com/zold-io/java-api/issues/36) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/java-api/issues/36#issuecomment-428504312))

@ypshenychka This is what I know about this job in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#36](https://github.com/zold-io/java-api/issues/36) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3mon
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will receive 15 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CAZUREFND?q=%7Bjob%3A%27gh%3Azold-io%2Fjava-api%2336%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by carlosmiranda** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@carlosmiranda thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
