### PR TITLE
#4 - introduce WalletsIn skeleton

### PR DESCRIPTION
**Pull request by t-izbassar**
This is initial skeleton implementation for #4. Decoupled it to two new puzzles.

### CODE REVIEW

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#10](https://github.com/zold-io/java-api/issues/10) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job [#10](https://github.com/zold-io/java-api/issues/10) is already in scope

**Comment by llorllale** [comment]
@t-izbassar I pushed a commit to `master` while answering your question in #8. Can you please update this branch with `master`?

**Comment by t-izbassar** [comment]
@llorllale done.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#10` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#10` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#10](https://github.com/zold-io/java-api/issues/10) is now out of scope

**Pull request merged**
