### PR TITLE
#6 Wallet skeleton, unit test

### PR DESCRIPTION
**Pull request by carlosmiranda**
#6: Added skeleton of `Wallet`.

* Added `Wallet.File` class
* Added `File.id()` implementation
* Added unit test and puzzles

### CODE REVIEW

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#14](https://github.com/zold-io/java-api/issues/14) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#14](https://github.com/zold-io/java-api/issues/14) is already in scope

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#14` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#14` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#14](https://github.com/zold-io/java-api/issues/14) is now out of scope

**Pull request merged**
